### ISSUE TITLE
Support for asyncio

### ISSUE THREAD

**Issue by tcareynokia** [nikipore/stompest#37]
I have seen where there is support for the Twisted framework. Is there plans to move to asyncio in Python 3.x?

**Comment by nikipore** [comment]
I have pondered with this idea a couple of times myself.

But I would view an `asyncio` client as an alternative to the Twisted `async` client rather than a replacement. I guess when Twisted has elapsed some more time in Python 3 world, other projects will demonstrate how Twisted and `asyncio` can peacefully coexist.

I am not going to implement it anytime soon because I am way too busy in my main job. But I am accepting pull requests and, if need be, going to walk the extra mile to integrate them properly. As I recently did with porting `stompest` to Python 3 based upon [this pull request](https://github.com/nikipore/stompest/issues/20).

**Comment by tcareynokia** [comment]
Ok - thanks for the feedback - I did implement this with the twisted asyncioreactor btw..
