### ISSUE TITLE
Asynch examples on ActiveMQ - Artemis

### ISSUE THREAD

**Issue by emmanuel-lopez** [nikipore/stompest#39]
Its possible that ActiveMQ Artemis will eventually take over and become Active MQ 6.  Sync messaging works well but when I try to do the async examples it doesn't seem to work properly on Artemis.

I also tried changing to the naming used on Artemis for JMS mapping, ie: /queue/testIn to jms.queue.testIn

 I've tried it on Artemis 1.5.3 and 2.1.0.  Here is a snippet of the transfer.py executing.

ActiveMQ Example
`DEBUG:stompest.async.listener:Handler for message ID:host-63961-1495574070738-3:1:-1:1:9 complete.
DEBUG:stompest.async.protocol:Received MESSAGE frame [headers={u'priority': u'4', u'timestamp': u'1495574098692', u'destination': u'/queue/testIn', u'message-id': u'ID:host-63961-1495574070738-3:1:-1:1:10', u'expires': u'0'}, body='{"count": 9}', version=1.0]`

Artemis Example:
`DEBUG:stompest.async.protocol:Received MESSAGE frame [headers={u'expires': u'0', u'timestamp': u'1495575970275', u'receipt': u'message-9', u'persistent': u'false', u'priority': u'4', u'destination': u'/queue/testIn', u'redelivered': u'false', u'message-id': u'2147483999', u'subscription': u'subscription//queue/testIn'}, body='{"count": 9}', version=1.0]
ERROR:stompest.async.client:Ignoring message (no handler found): 2147483999 [MESSAGE frame [headers={u'expires': u'0', u'timestamp': u'1495575970275', u'receipt': u'message-9', u'persistent': u'false', u'priority': u'4', u'destination': u'/queue/testIn', u'redelivered': u'false', u'message-id': u'2147483999', u'subscription': u'subscription//queue/testIn'}, body='{"count": 9}', version=1.0]]`

**Comment by nikipore** [comment]
The Artemis frame contains two Stomp protocol headers I wouldn't expect. First, it loops through the `receipt` header. This shouldn't be a problem, though. Second, the `subscription` header is added although no `id` header was given (which is optional in Stomp 1.0). The [protocol specification](https://stomp.github.io/stomp-specification-1.0.html) says:

> You can also specify an id header which can then later on be used to UNSUBSCRIBE from the specific subscription as you may end up with overlapping subscriptions using selectors with the same destination. If an id header is supplied then Stomp brokers should append a subscription header to any MESSAGE commands which are sent to the client so that the client knows which subscription the message relates to.

To sum up, you can/should do either of the following:

1. File a bug to Artemis because their implementation of STOMP 1.0 isn't correct and wait until it's fixed.
2. Add an explicit `id`(properly coded, that would be `StompSpec.ID_HEADER`) header to work around the Artemis bug.

Probably you shouldn't use Stomp 1.0 in the first place because it's an under-specified protocol (no `NACK` frames, no header escaping, no heartbeating). Actually, I recommend to start new projects on Stomp 1.2 or (if your broker doesn't support it) Stomp 1.1.
